### PR TITLE
add Large deal button on the top

### PR DESCRIPTION
**Pull request by wangjiad**
add Large deal button on the top, and add some css to custom it, feel
free to change style in .css file:)

### CODE REVIEW

**Comment by wangjiad** [comment]
Forgot SS, 
image

**Comment by siebertc** [comment]
This group repo has some added code to the CSS and my other commits! That's causing conflicts on the AcesUp.css. You'll need to fetch the changes from the group master branch and merge and take care of the conflicts.

**Comment by wangjiad** [comment]
image
I am not able to update from original repo

**Comment by siebertc** [comment]
Alex helped me with the through with command line - I don't know how to do it with the Desktop App.

This is a good tool to look over: https://www.git-tower.com/blog/git-cheat-sheet/
Shows commands for the git command line,

and the commands here should help you out: 
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b wangjiad-master master
git pull https://github.com/wangjiad/Group18-2.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff wangjiad-master
git push origin master

**Comment by wangjiad** [comment]
Command seems doesn't work.. :(
image

**Comment by siebertc** [comment]
Doesn't look like you're in your local directory for the assignment.

Try changing to: C:\Users\lostchoice1\Documents\GitHub\YOUR_LOCAL_REPO

and run the git commands from there.

**Comment by wangjiad** [comment]
image
Shows everything is updated, but it still not able to merge.

**Comment by siebertc** [comment]
You're on the right path it looks like... though I'm not sure why it's not merging.

Try looking through this: http://dont-be-afraid-to-commit.readthedocs.org/en/latest/git/conflicts.html
has some good information on resolving conflicts.

**Comment by wangjiad** [comment]
Sorry, I still can not figure it out. :(

**Comment by wangjiad** [comment]
You guys can look over my lastest two commit change for deal button, make pull request for me if you guys think it is working. After trying much command, I can not even change branch anymore. :( github is hard to use.

**Comment by luayalshawi** [comment]
Try using Source Tree. It's a lot better than Github Desketep. You might be able to fix the conflix using source Tree.

**Comment by siebertc** [comment]
The group repo is back up to the last commit - please fetch the data off of
it NOW into your local repository, and CLONE your local repository. from
there make your changes and make a pull request.

**Comment by wangjiad** [comment]
how to fetch the data from original repo? Even I fork again, my repo still not change.

**Comment by wangjiad** [comment]
The time is almost out, I think just turn what we got for now. I am going to sleep. Good night, guys :)

**Pull request closed without merging**
