### PR TITLE
add help button first version

### PR DESCRIPTION
**Pull request by wangjiad**
simply add help button and text, I will try make it more comfortable for
using later

### CODE REVIEW

**Comment by alxngyn** [comment]
Nice commit, maybe add a SS next time you do a Pull Request so it's easier to just click on the green button

**Comment by wangjiad** [comment]
What is "SS"?

**Comment by alxngyn** [comment]
sorry, 
SS=screenshot

**Comment by wangjiad** [comment]
Ok

**Comment by siebertc** [comment]
Just tested it, it might be better if all of the rules could be condensed into one message. Multiple clicks could get a little irritating when looking back through the rules. :) Otherwise looks good

**Comment by wangjiad** [comment]
Because the rule is complicated, that is a lot text, it may make user feel uncomfortable if show a lots information in same time. That is what I think, never mind, I am still working on it now. Thank you for advice. :)

**Comment by luayalshawi** [comment]
I can see the changes. Better than before.

**Pull request merged**
